name: Render Deployment

on:
  push:
    branches: [ main ]  # Triggers when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "${{ secrets.https://api.render.com/deploy/srv-d7mdaupo3t8c73e455og?key=54_ebYtelAI}}"
